name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-noble-ros-jazzy-ros-base
    steps:
      - name: Build pb_omni_pid_pursuit_controller
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: pb_omni_pid_pursuit_controller
          target-ros2-distro: jazzy
